### ISSUE TITLE
8-direction move

### ISSUE THREAD

**Issue by zewa666** [GaryStanton/phaser3-merged-input#15]
hi, let me first say its a great plugin. I'm using it together with the phaser-grid-engine plugin to build a simple top down rpg. Now it would be great if your plugin could also handle diagonal movement.

**Comment by GaryStanton** [comment]
I’m thrilled to hear you’re using the plugin for your game. I’m not sure what you’re asking for however, diagonal movement is already supported!

**Comment by zewa666** [comment]
well I didnt see any diagonal example in your demo so I honestly have no clue how its supposed to work. Does it mean that in case of diagonal DOWN + RIGHT both directions would be TRUE?

**Comment by GaryStanton** [comment]
Yes, that’s one way of handling it. It depends how you’re game interprets what comes back in the data. There’s also a direction property that shows the compass points, that might be more helpful for you.
I’m on the road at the moment so I can’t into the code right now, but dump out the player object and you should see a few different options. 
If you’re after an explicit keybinding for diagonals, that might be a bit more tricky… I could look at adding that if that’s what you’re after.
