### ISSUE TITLE
Handle `any key`

### ISSUE THREAD

**Issue by zewa666** [GaryStanton/phaser3-merged-input#23]
hey there @GaryStanton

I was wondering of how one would check for any key, mouse or gamepad press. e.g. when starting a game and the intro says `press any key to continue`

**Comment by GaryStanton** [comment]
Hi @zewa666,
Could you just check for anything in interaction.pressed? 
That should contain a button press for a single tick, keyboard, game pad or mouse. You may want to exclude direction buttons, but it should work fine.

**Comment by zewa666** [comment]
so essentially `interaction.pressed !== ""`?  I'll try that, makes sense

**Comment by GaryStanton** [comment]
Yes, something along those lines… you’ve caught me while I’m away again so can’t test right now, but I think that should work for you.

**Comment by GaryStanton** [comment]
@zewa666 did you get that working? Just checking I can close the issue.

**Comment by zewa666** [comment]
sry, yes all good

**Comment by GaryStanton** [comment]
Great, thanks!
Let me know when you release the game you’re working on. It’ll be great to see the plug-in in use elsewhere. ;)
